service: polttoaine-saa-backend
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  apiName: polttoaine-saa-${self:provider.stage}
  apiKeys:
    - polttoaine-saa-${self:provider.stage}-key

  stage: ${opt:stage, 'dev'}
  region: eu-central-1

  usagePlan:
    quota:
      limit: 50000
      period: MONTH
    throttle:
      burstLimit: 20
      rateLimit: 10

custom:
  webpack:
    includeModules: true

plugins:
  - serverless-webpack

functions:
  getStations:
    handler: src/handler.getStations
    events:
      - http:
          path: stations
          method: GET
          private: true
